package QuanLiNhanVien;

import BLL.NhanVienBLL;
import DAO.KhachHangDAO;
import DAO.NhanVienDAO;
import DAO.ThucDonDAO;
import Model.KhachHang;
import Model.NhanVien;
import Model.ThucDon;
import QuanLiTaiKhoan.TTCaNhan;
import TrangChinh.Dang_Nhap;
import TrangChinh.MagementForm;
import TrangChinh.OrderFormChoose;
import TrangChinh.StaticsFormChoose;
import TrangChinh.Welecome;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vomin
 */
public class QLNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form NV
     */
    public QLNhanVien() {
        initComponents();      
        new NhanVienBLL().fillCombobox(cbbChucvu);   
        //autoIdNV();
        formatJdateChooser();
        showTable();
    }

    private void formatJdateChooser(){
        //MMMMM d, yyyy format mặc định
        Date date=java.util.Calendar.getInstance().getTime();
        dcNgaysinh.setDate(date);
    }
    
    private void createTable(ArrayList<NhanVien> nhanViens){
        DefaultTableModel defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; //To change body of generated methods, choose Tools | Templates.
            }
            
        };      
        defaultTableModel.addColumn("Mã nhân viên");
        defaultTableModel.addColumn("Tên nhân viên");
        defaultTableModel.addColumn("Ngày sinh");
        defaultTableModel.addColumn("Giới tính");
        defaultTableModel.addColumn("Địa chỉ");
        defaultTableModel.addColumn("Số điện thoại");
        defaultTableModel.addColumn("Chức vụ");
        defaultTableModel.addColumn("ID");
        defaultTableModel.addColumn("Giới tính");
        defaultTableModel.setRowCount(0);
        for(NhanVien nhanVien : nhanViens){
            defaultTableModel.addRow(new Object[]{nhanVien.getManv(), nhanVien.getTennv(), nhanVien.getNgaysinh(), nhanVien.getGioitinh(),
                nhanVien.getDiachi(), nhanVien.getSdt(), nhanVien.getChucvu(), nhanVien.getIdcanhan(), nhanVien.getGioitinh()});   
        }
        tableQLNV.setModel(defaultTableModel);
    }
    
    ArrayList<NhanVien> nhanViens = new ArrayList<>(); 
    private void showTable(){
        NhanVienDAO nhanVienDAO = new NhanVienDAO();
        ArrayList<NhanVien> nhanViens = new ArrayList<NhanVien>();
        nhanViens = nhanVienDAO.toanbodanhsach();
        createTable(nhanViens);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnThem = new com.k33ptoo.components.KButton();
        txtTimkiem = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableQLNV = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtManv = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtTennv = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtDiachi = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtSdt = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnSua = new com.k33ptoo.components.KButton();
        btnLammoi = new com.k33ptoo.components.KButton();
        btnXoa = new com.k33ptoo.components.KButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        rdbNam = new javax.swing.JRadioButton();
        rdbNu = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        cbbChucvu = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        rdbCasang = new javax.swing.JRadioButton();
        rdbCachieu = new javax.swing.JRadioButton();
        rdbCatoi = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        btnTimkiem = new com.k33ptoo.components.KButton();
        jLabel32 = new javax.swing.JLabel();
        btnXuatExcel = new com.k33ptoo.components.KButton();
        dcNgaysinh = new com.toedter.calendar.JDateChooser();
        lbAnh = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        kButton8 = new com.k33ptoo.components.KButton();
        lbStatics = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnStatics = new com.k33ptoo.components.KButton();
        lbAccount = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnAccount = new com.k33ptoo.components.KButton();
        lbDashboard = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnLogout = new com.k33ptoo.components.KButton();
        lbManagement = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnManagement = new com.k33ptoo.components.KButton();
        lbOrder = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnOrder = new com.k33ptoo.components.KButton();
        lbWorkbench = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnWorkbench = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Thêm");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 690, 50, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Cake");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 50, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Sửa");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 690, 50, 20));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel25.setText("Staff Manager");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 360, 50));

        btnThem.setkBorderRadius(25);
        btnThem.setkEndColor(new java.awt.Color(255, 153, 255));
        btnThem.setkHoverEndColor(new java.awt.Color(255, 153, 51));
        btnThem.setkHoverForeGround(new java.awt.Color(255, 102, 102));
        btnThem.setkHoverStartColor(new java.awt.Color(255, 51, 51));
        btnThem.setkStartColor(new java.awt.Color(255, 102, 51));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 680, 150, 40));

        txtTimkiem.setOpaque(false);
        jPanel1.add(txtTimkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 490, 40));
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 30, 30));

        tableQLNV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tableQLNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Tên NV", "Ngay sinh", "Địa chỉ", "SĐT", "Ca làm việc", "Chức vụ", "CCCD"
            }
        ));
        tableQLNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableQLNVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableQLNV);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, 660, 380));

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Thông tin nhân viên");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Làm mới");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 690, 90, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Xóa");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 690, 50, 20));

        txtManv.setEditable(false);
        txtManv.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txtManv.setForeground(new java.awt.Color(0, 204, 204));
        txtManv.setBorder(null);
        txtManv.setOpaque(false);
        jPanel1.add(txtManv, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 230, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("SĐT");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 180, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 230, 20));

        txtTennv.setBorder(null);
        txtTennv.setOpaque(false);
        jPanel1.add(txtTennv, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 230, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 230, 20));

        txtDiachi.setText("Đông Hà");
        txtDiachi.setBorder(null);
        txtDiachi.setOpaque(false);
        jPanel1.add(txtDiachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 230, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 230, 40));

        txtSdt.setText("090324545");
        txtSdt.setBorder(null);
        txtSdt.setOpaque(false);
        jPanel1.add(txtSdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 230, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 230, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Nhập mã nhân viên");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 180, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Nhập CCCD/CMND");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 120, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Địa chỉ");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 180, 20));

        btnSua.setkBorderRadius(25);
        btnSua.setkEndColor(new java.awt.Color(102, 204, 255));
        btnSua.setkHoverEndColor(new java.awt.Color(255, 102, 153));
        btnSua.setkHoverForeGround(new java.awt.Color(204, 102, 255));
        btnSua.setkHoverStartColor(new java.awt.Color(255, 102, 255));
        btnSua.setkStartColor(new java.awt.Color(255, 153, 102));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 680, 150, 40));

        btnLammoi.setkBorderRadius(25);
        btnLammoi.setkEndColor(new java.awt.Color(102, 204, 255));
        btnLammoi.setkHoverEndColor(new java.awt.Color(255, 102, 153));
        btnLammoi.setkHoverForeGround(new java.awt.Color(204, 102, 255));
        btnLammoi.setkHoverStartColor(new java.awt.Color(255, 102, 255));
        btnLammoi.setkStartColor(new java.awt.Color(255, 102, 51));
        btnLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiActionPerformed(evt);
            }
        });
        jPanel1.add(btnLammoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 680, 150, 40));

        btnXoa.setkBorderRadius(25);
        btnXoa.setkEndColor(new java.awt.Color(102, 204, 255));
        btnXoa.setkHoverEndColor(new java.awt.Color(255, 102, 153));
        btnXoa.setkHoverForeGround(new java.awt.Color(204, 102, 255));
        btnXoa.setkHoverStartColor(new java.awt.Color(255, 102, 255));
        btnXoa.setkStartColor(new java.awt.Color(255, 102, 102));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 680, 150, 40));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Drinks");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 640, 50, 20));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Ngày sinh");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 180, 20));

        buttonGroup2.add(rdbNam);
        rdbNam.setText("Nam");
        jPanel1.add(rdbNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, -1, -1));

        buttonGroup2.add(rdbNu);
        rdbNu.setText("Nữ");
        jPanel1.add(rdbNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Giới tính");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 180, 20));

        txtID.setBorder(null);
        txtID.setOpaque(false);
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 230, 30));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 230, 20));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("Nhập tên nhân viên");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 180, 20));

        cbbChucvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbChucvuActionPerformed(evt);
            }
        });
        jPanel1.add(cbbChucvu, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 230, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("Chức vụ");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 180, 20));

        buttonGroup1.add(rdbCasang);
        rdbCasang.setText("Ca sáng");
        jPanel1.add(rdbCasang, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, -1, -1));

        buttonGroup1.add(rdbCachieu);
        rdbCachieu.setText("Ca chiều");
        jPanel1.add(rdbCachieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, -1, -1));

        buttonGroup1.add(rdbCatoi);
        rdbCatoi.setText("Ca tối");
        jPanel1.add(rdbCatoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("Ca làm việc");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 180, 20));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Tìm kiếm");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 80, 90, 40));

        btnTimkiem.setToolTipText("");
        btnTimkiem.setkBorderRadius(25);
        btnTimkiem.setkEndColor(new java.awt.Color(102, 0, 102));
        btnTimkiem.setkHoverEndColor(new java.awt.Color(255, 153, 51));
        btnTimkiem.setkHoverForeGround(new java.awt.Color(255, 102, 102));
        btnTimkiem.setkHoverStartColor(new java.awt.Color(255, 51, 51));
        btnTimkiem.setkStartColor(new java.awt.Color(51, 204, 255));
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });
        jPanel1.add(btnTimkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 110, 40));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Xuất Excel");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 690, 130, 20));

        btnXuatExcel.setkBorderRadius(25);
        btnXuatExcel.setkEndColor(new java.awt.Color(0, 102, 51));
        btnXuatExcel.setkHoverEndColor(new java.awt.Color(255, 102, 153));
        btnXuatExcel.setkHoverForeGround(new java.awt.Color(204, 102, 255));
        btnXuatExcel.setkHoverStartColor(new java.awt.Color(255, 102, 255));
        btnXuatExcel.setkStartColor(new java.awt.Color(0, 204, 102));
        btnXuatExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatExcelActionPerformed(evt);
            }
        });
        jPanel1.add(btnXuatExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 680, 150, 40));

        dcNgaysinh.setDateFormatString("dd-MM-yyyy");
        jPanel1.add(dcNgaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 230, -1));

        lbAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAnhMouseClicked(evt);
            }
        });
        jPanel1.add(lbAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 200, 160));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Ảnh nhân viên");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, -1, -1));

        kGradientPanel1.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkBorderRadius(50);
        kGradientPanel1.setkEndColor(new java.awt.Color(204, 153, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 153, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton8.setkBorderRadius(15);
        kButton8.setkEndColor(new java.awt.Color(0, 255, 204));
        kButton8.setkHoverEndColor(new java.awt.Color(153, 51, 255));
        kButton8.setkHoverForeGround(new java.awt.Color(204, 102, 255));
        kButton8.setkHoverStartColor(new java.awt.Color(204, 102, 255));
        kGradientPanel1.add(kButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 150, 210));

        lbStatics.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbStatics.setForeground(new java.awt.Color(255, 255, 255));
        lbStatics.setText("Statistics");
        kGradientPanel1.add(lbStatics, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 120, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\vomin\\OneDrive\\Máy tính\\icons8-account-18.png")); // NOI18N
        kGradientPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 30, 50));

        btnStatics.setkBorderRadius(0);
        btnStatics.setkEndColor(new java.awt.Color(204, 153, 255));
        btnStatics.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        btnStatics.setkHoverForeGround(new java.awt.Color(255, 102, 255));
        btnStatics.setkHoverStartColor(new java.awt.Color(255, 153, 255));
        btnStatics.setkStartColor(new java.awt.Color(204, 153, 255));
        btnStatics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaticsActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnStatics, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 210, 50));

        lbAccount.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbAccount.setForeground(new java.awt.Color(255, 255, 255));
        lbAccount.setText("Account");
        kGradientPanel1.add(lbAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 120, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\vomin\\OneDrive\\Máy tính\\icons8-user-account-18.png")); // NOI18N
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 30, 50));

        btnAccount.setkBorderRadius(0);
        btnAccount.setkEndColor(new java.awt.Color(204, 153, 255));
        btnAccount.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        btnAccount.setkHoverForeGround(new java.awt.Color(255, 102, 255));
        btnAccount.setkHoverStartColor(new java.awt.Color(255, 163, 255));
        btnAccount.setkStartColor(new java.awt.Color(204, 153, 255));
        btnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 210, 50));

        lbDashboard.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lbDashboard.setText("Log out");
        kGradientPanel1.add(lbDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 120, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\vomin\\Downloads\\icons8-logout-rounded-left-24.png")); // NOI18N
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 30, 50));

        btnLogout.setkBorderRadius(0);
        btnLogout.setkEndColor(new java.awt.Color(204, 153, 255));
        btnLogout.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        btnLogout.setkHoverForeGround(new java.awt.Color(255, 102, 255));
        btnLogout.setkHoverStartColor(new java.awt.Color(255, 153, 255));
        btnLogout.setkStartColor(new java.awt.Color(204, 153, 255));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 210, 50));

        lbManagement.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbManagement.setForeground(new java.awt.Color(255, 255, 255));
        lbManagement.setText("Management");
        kGradientPanel1.add(lbManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 120, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\vomin\\OneDrive\\Máy tính\\icons8-add-user-male-18.png")); // NOI18N
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 30, 50));

        btnManagement.setkBorderRadius(0);
        btnManagement.setkEndColor(new java.awt.Color(204, 153, 255));
        btnManagement.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        btnManagement.setkHoverForeGround(new java.awt.Color(255, 102, 255));
        btnManagement.setkHoverStartColor(new java.awt.Color(255, 153, 255));
        btnManagement.setkStartColor(new java.awt.Color(204, 153, 255));
        btnManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagementActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 210, 50));

        lbOrder.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbOrder.setForeground(new java.awt.Color(255, 255, 255));
        lbOrder.setText("Order");
        kGradientPanel1.add(lbOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 120, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\vomin\\OneDrive\\Máy tính\\icons8-shopping-cart-18.png")); // NOI18N
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 30, 50));

        btnOrder.setkBorderRadius(0);
        btnOrder.setkEndColor(new java.awt.Color(204, 153, 255));
        btnOrder.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        btnOrder.setkHoverForeGround(new java.awt.Color(255, 102, 204));
        btnOrder.setkHoverStartColor(new java.awt.Color(255, 153, 255));
        btnOrder.setkStartColor(new java.awt.Color(204, 153, 255));
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 210, 50));

        lbWorkbench.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbWorkbench.setForeground(new java.awt.Color(255, 255, 255));
        lbWorkbench.setText("Workbench");
        kGradientPanel1.add(lbWorkbench, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\vomin\\OneDrive\\Máy tính\\icons8-home-18.png")); // NOI18N
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 30, 50));

        btnWorkbench.setkBorderRadius(0);
        btnWorkbench.setkEndColor(new java.awt.Color(204, 153, 255));
        btnWorkbench.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        btnWorkbench.setkHoverForeGround(new java.awt.Color(255, 102, 255));
        btnWorkbench.setkHoverStartColor(new java.awt.Color(255, 153, 255));
        btnWorkbench.setkStartColor(new java.awt.Color(204, 153, 255));
        btnWorkbench.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkbenchActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnWorkbench, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 210, 50));

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 250, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        // TODO add your handling code here:
        NhanVienDAO nvDAO = new NhanVienDAO();
        nhanViens.clear();
        try {
            nhanViens = nvDAO.timkiemNhanViens(txtTimkiem.getText());
            createTable(nhanViens);
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void btnXuatExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatExcelActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Chúng em làm vẫn chưa kịp ạ!");
    }//GEN-LAST:event_btnXuatExcelActionPerformed

    private void tableQLNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableQLNVMouseClicked
        // TODO add your handling code here:
        int row = tableQLNV.getSelectedRow();
        try {
            if(row != -1){            
            txtManv.setText((String) tableQLNV.getValueAt(row, 0));
            txtTennv.setText((String) tableQLNV.getValueAt(row, 1));
            dcNgaysinh.setDate((Date) tableQLNV.getValueAt(row, 2));
            txtDiachi.setText((String) tableQLNV.getValueAt(row, 4));
            txtSdt.setText((String) tableQLNV.getValueAt(row, 5));
            String clv = (String) tableQLNV.getValueAt(row, 3);
            if(clv.equals(rdbCasang.getText()))
                rdbCasang.isSelected();
            else if(clv.equals(rdbCachieu.getText()))
                rdbCachieu.isSelected();
            else 
                rdbCatoi.isSelected();
            String cv = (String) tableQLNV.getValueAt(row, 6);
            cbbChucvu.setSelectedItem(cv);
            txtID.setText((String) tableQLNV.getValueAt(row, 7));
            String gt = (String) tableQLNV.getValueAt(row, 8);
            if(gt.equals(rdbNam.getText()))
                rdbNam.setSelected(true);
            else
                rdbNu.setSelected(true);
            NhanVien nvClick = new NhanVienDAO().timkiemtheoID((String) tableQLNV.getValueAt(row, 0));
            ImageIcon imageIcon = new ImageIcon(nvClick.getAnh());
            Image image = imageIcon.getImage();
            Image newimg = image.getScaledInstance(200, 160,  java.awt.Image.SCALE_SMOOTH);
            imageIcon = new ImageIcon(newimg);
            lbAnh.setIcon(imageIcon);            
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tableQLNVMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        NhanVien nhanVien = new NhanVien();
        CheckInputNhanVien checkInputNhanVien = new CheckInputNhanVien();
        try{
            nhanVien.setIdcanhan(txtManv.getText());
            if(!checkInputNhanVien.checkCMNDvaCCCD(txtID.getText())){
                JOptionPane.showMessageDialog(rootPane, "Số chứng minh nhân viên không hợp lệ! Yêu cầu nhập lại");
                txtID.setText("");
            }
            else{
                    nhanVien.setTennv(txtTennv.getText());
                    if(!checkInputNhanVien.checkChuoiKhongSo(txtTennv.getText())){
                        JOptionPane.showMessageDialog(rootPane, "Định dạng tên không hợp lệ (Có số)! Yêu cầu nhập lại");
                        txtTennv.setText("");
                    }
                    else {
                        nhanVien.setDiachi(txtDiachi.getText());
                        if(txtDiachi.getText().equals("")){
                            JOptionPane.showMessageDialog(rootPane, "Địa chỉ rỗng");
                            txtDiachi.setText("");
                        }
                        nhanVien.setSdt(txtSdt.getText());
                        if(!checkInputNhanVien.checkChuoiSDT(txtSdt.getText())){
                            JOptionPane.showMessageDialog(rootPane, "Định dạng số điện thoại không hợp lệ! Yêu cầu nhập lại");
                            txtSdt.setText("");
                        }
                        else{
                            if(!rdbNam.isSelected() && !rdbNu.isSelected()){
                                JOptionPane.showMessageDialog(rootPane, "Chưa chọn giới tính cho nhân viên! Yêu cầu chọn");
                            }
                            else{
                                String gioitinh ="";
                                if(rdbNam.isSelected())
                                gioitinh = "Nam";
                                if(rdbNu.isSelected())
                                gioitinh = "Nữ";
                                nhanVien.setGioitinh(gioitinh);
                                int calamviec = 0;                                    
                                if(rdbCasang.isSelected() && rdbCachieu.isSelected() && rdbCatoi.isSelected()){
                                    JOptionPane.showMessageDialog(rootPane, "Chưa chọn ca làm việc cho nhân viên! Yêu cầu chọn");
                                }
                                else{                                   
                                    String clv ="";
                                    if(rdbCasang.isSelected())
                                        clv = rdbCasang.getText();
                                    if(rdbCasang.isSelected())
                                        clv = "Ca sáng";
                                    if(rdbCatoi.isSelected())
                                        clv = "Ca tối";
                                    nhanVien.setGioitinh(gioitinh);
                                    java.sql.Date sqldateNS = new java.sql.Date(dcNgaysinh.getDate().getTime());
                                    nhanVien.setNgaysinh(sqldateNS);
                                    if(lbAnh.getIcon()!=null){
                                        nhanVien.setAnh(pathImage);
                                        new NhanVienDAO().them(nhanVien);
                                        JOptionPane.showMessageDialog(rootPane, "Thêm nhân viên thành công");
                                        showTable();

                                    }else{                          
                                        JOptionPane.showMessageDialog(null, "Chưa cập nhật ảnh");
                                    }
                                }                                  
                            }
                        }
                    }                                      
                }
        }catch (Exception e){
            System.out.println(e.getMessage());
            System.out.println("Thêm vào không thành công");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    String idAnh = null;
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        NhanVien nhanVien = new NhanVienDAO().timkiemtheoID(txtManv.getText());
        idAnh = nhanVien.getAnh();
        CheckInputNhanVien checkInputNhanVien = new CheckInputNhanVien();
        try{
            nhanVien.setIdcanhan(txtID.getText());
            if(!checkInputNhanVien.checkCMNDvaCCCD(txtID.getText())){
                JOptionPane.showMessageDialog(rootPane, "Số chứng minh nhân viên không hợp lệ! Yêu cầu nhập lại");
                txtID.setText("");
            }
            else{
                    nhanVien.setTennv(txtTennv.getText());
                    if(!checkInputNhanVien.checkChuoiKhongSo(txtTennv.getText())){
                        JOptionPane.showMessageDialog(rootPane, "Định dạng tên không hợp lệ (Có số)! Yêu cầu nhập lại");
                        txtTennv.setText("");
                    }
                    else {
                        nhanVien.setDiachi(txtDiachi.getText());
                        nhanVien.setChucvu((String) cbbChucvu.getSelectedItem());
                        if(txtDiachi.getText().equals("")){
                            JOptionPane.showMessageDialog(rootPane, "Địa chỉ rỗng");
                            txtDiachi.setText("");
                        }
                        nhanVien.setSdt(txtSdt.getText());
                        if(!checkInputNhanVien.checkChuoiSDT(txtSdt.getText())){
                            JOptionPane.showMessageDialog(rootPane, "Định dạng số điện thoại không hợp lệ! Yêu cầu nhập lại");
                            txtSdt.setText("");
                        }
                        else{
                            if(!rdbNam.isSelected() && !rdbNu.isSelected()){
                                JOptionPane.showMessageDialog(rootPane, "Chưa chọn giới tính cho nhân viên! Yêu cầu chọn");
                            }
                            else{
                                String gioitinh ="";
                                if(rdbNam.isSelected())
                                gioitinh = "Nam";
                                if(rdbNu.isSelected())
                                gioitinh = "Nữ";
                                nhanVien.setGioitinh(gioitinh);
                                int calamviec = 0;                                    
                                if(!rdbCasang.isSelected() && !rdbCachieu.isSelected() && !rdbCatoi.isSelected()){
                                    JOptionPane.showMessageDialog(rootPane, "Chưa chọn ca làm việc cho nhân viên! Yêu cầu chọn");
                                }
                                else{
                                    String clv ="";
                                    if(rdbCasang.isSelected())
                                        clv = rdbCasang.getText();
                                    if(rdbCasang.isSelected())
                                        clv = "Ca sáng";
                                    if(rdbCatoi.isSelected())
                                        clv = "Ca tối";
                                    nhanVien.setGioitinh(gioitinh);
                                    java.sql.Date sqldateNS = new java.sql.Date(dcNgaysinh.getDate().getTime());
                                    nhanVien.setNgaysinh(sqldateNS);
                                    if(lbAnh.getIcon()!=null){
                                        nhanVien.setAnh(pathImage);
                                        new NhanVienDAO().sua(nhanVien);
                                        JOptionPane.showMessageDialog(rootPane, "Sửa nhân viên thành công");
                                        showTable();
                                    }else{                          
                                        JOptionPane.showMessageDialog(null, "Chưa cập nhật ảnh");
                                    };
                                }
                                    
                            }
                        }
                    }                                      
                }
        }catch (Exception e){
            System.out.println(e.getMessage());
            System.out.println("Thêm vào không thành công");
            e.printStackTrace();
        }        
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiActionPerformed
        // TODO add your handling code here:
        autoIdNV();
        txtDiachi.setText("");
        txtID.setText("");
        txtSdt.setText("");
        txtTennv.setText("");
        txtTimkiem.setText("");
        cbbChucvu.setSelectedIndex(0);
        rdbCachieu.setSelected(false);
        rdbCasang.setSelected(false);
        rdbCatoi.setSelected(false);
        rdbNam.setSelected(false);
        rdbNu.setSelected(false);
    }//GEN-LAST:event_btnLammoiActionPerformed

        public void autoIdNV(){
        try {               
                String idcuoicung = new NhanVienDAO().tkcuoidanhsach();
                if(cbbChucvu.getSelectedIndex()!=-1){
                    //cbbChucvu.getSelectedIndex();
                    String data = "";
                    data = (String) cbbChucvu.getItemAt(cbbChucvu.getSelectedIndex());
                    String[] idsplit = data.split(" "); 
                    char tk2 = Character.toUpperCase(idsplit[2].charAt(0));
                    char tk3 = Character.toUpperCase(idsplit[3].charAt(0));
                    String idnumberlast = "";
                    for(int i=0; i < idcuoicung.length(); i++) {
                        Boolean flag = Character.isDigit(idcuoicung.charAt(i));
                        if(Character.toString(idcuoicung.charAt(idcuoicung.length()-2)).equals("0")) {
                            idnumberlast = ""+ idcuoicung.charAt(idcuoicung.length()-1);                         
                        }else if(Character.toString(idcuoicung.charAt(idcuoicung.length()-3)).equals("0")){
                              idnumberlast = ""+ idcuoicung.charAt(idcuoicung.length()-2) + idcuoicung.charAt(idcuoicung.length()-1);
                        }else{
                              idnumberlast = ""+ idcuoicung.charAt(idcuoicung.length()-2) + idcuoicung.charAt(idcuoicung.length()-1) + idcuoicung.charAt(idcuoicung.length());
                        }
            
                    }
                    int chuoicuoi = Integer.parseInt(idnumberlast)+1;
                    if(chuoicuoi<9){
                        idnumberlast = "00"+chuoicuoi;
                    }else if(chuoicuoi>=9 && chuoicuoi <=99){
                        idnumberlast = "0"+chuoicuoi;
                    }else
                        idnumberlast = ""+chuoicuoi;
                    txtManv.setText("NV"+tk2+tk3+idnumberlast);
                }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn xóa?");
        if(confirm ==JOptionPane.YES_OPTION){
            new NhanVienDAO().xoa(txtManv.getText());
            JOptionPane.showMessageDialog(rootPane, "Xóa nhân viên thành công");
            showTable();
        }        
    }//GEN-LAST:event_btnXoaActionPerformed

    String pathImage = null;
    private void lbAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAnhMouseClicked
        // TODO add your handling code here:
        try {                     
        JFileChooser anhThucdonChooser = new JFileChooser();
       // anhThucdonChooser.showOpenDialog(null);         
        anhThucdonChooser.setCurrentDirectory(new File("D:\\Pictrue\\Project\\Course Project\\Java\\NhanVien"));
        anhThucdonChooser.setFileFilter(new FileNameExtensionFilter("Supported extension", "jpg", "png"));
        anhThucdonChooser.showSaveDialog(null);   
        File fileanh = anhThucdonChooser.getSelectedFile();
        String filepath = fileanh.getAbsolutePath();
        fileanh.getParentFile().mkdirs();
        if(fileanh == null){
            JOptionPane.showMessageDialog(rootPane, "Chưa cập nhật ảnh nhân viên");
        }
        else{
            ImageIcon imageNVicon = new ImageIcon(filepath);
            Image image = imageNVicon.getImage();
            Image newimg = image.getScaledInstance(245, 178,  java.awt.Image.SCALE_SMOOTH);
            imageNVicon = new ImageIcon(newimg);
            lbAnh.setIcon(imageNVicon);   
            pathImage = filepath;
            //thucDon.setAnh(filepath);
        }             
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lbAnhMouseClicked

    private void cbbChucvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbChucvuActionPerformed
        // TODO add your handling code here:
        autoIdNV();
    }//GEN-LAST:event_cbbChucvuActionPerformed

    private void btnStaticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaticsActionPerformed
        // TODO add your handling code here:
        new StaticsFormChoose().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStaticsActionPerformed

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        // TODO add your handling code here:
        new TTCaNhan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAccountActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new Dang_Nhap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagementActionPerformed
        // TODO add your handling code here:
        new MagementForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManagementActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // TODO add your handling code here:
        new OrderFormChoose().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnWorkbenchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkbenchActionPerformed
        // TODO add your handling code here:
        new Welecome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnWorkbenchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnAccount;
    private com.k33ptoo.components.KButton btnLammoi;
    private com.k33ptoo.components.KButton btnLogout;
    private com.k33ptoo.components.KButton btnManagement;
    private com.k33ptoo.components.KButton btnOrder;
    private com.k33ptoo.components.KButton btnStatics;
    private com.k33ptoo.components.KButton btnSua;
    private com.k33ptoo.components.KButton btnThem;
    private com.k33ptoo.components.KButton btnTimkiem;
    private com.k33ptoo.components.KButton btnWorkbench;
    private com.k33ptoo.components.KButton btnXoa;
    private com.k33ptoo.components.KButton btnXuatExcel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbbChucvu;
    private com.toedter.calendar.JDateChooser dcNgaysinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private com.k33ptoo.components.KButton kButton8;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lbAccount;
    private javax.swing.JLabel lbAnh;
    private javax.swing.JLabel lbDashboard;
    private javax.swing.JLabel lbManagement;
    private javax.swing.JLabel lbOrder;
    private javax.swing.JLabel lbStatics;
    private javax.swing.JLabel lbWorkbench;
    private javax.swing.JRadioButton rdbCachieu;
    private javax.swing.JRadioButton rdbCasang;
    private javax.swing.JRadioButton rdbCatoi;
    private javax.swing.JRadioButton rdbNam;
    private javax.swing.JRadioButton rdbNu;
    private javax.swing.JTable tableQLNV;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtManv;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtTennv;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables
}
