/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLiHoaDon;

import DAO.BanDAO;
import DAO.ChiTietHoaDonDAO;
import DAO.HoaDonDAO;
import DAO.KhachHangDAO;
import DAO.NhanVienDAO;
import DAO.ThucDonDAO;
import Model.Ban;
import Model.ChiTietHoaDon;
import Model.HoaDon;
import Model.KhachHang;
import Model.NhanVien;
import Model.ThucDon;
import QuanLiTaiKhoan.TTCaNhan;
import TrangChinh.Dang_Nhap;
import TrangChinh.MagementForm;
import TrangChinh.OrderFormChoose;
import TrangChinh.StaticsFormChoose;
import TrangChinh.Welecome;
import com.k33ptoo.components.KGradientPanel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Label;
import java.awt.SystemColor;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.NumberFormat;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.BevelBorder;
import javax.swing.border.Border;
import javax.swing.border.EtchedBorder;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vomin
 */
public class Order extends javax.swing.JFrame {
    /**
     * Creates new form Order
     */
    public Order() {
        initComponents();
        showListFood();
        System.out.println(""+thucDons.size());
        setIDHDAuto();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        lbManv.setText(Dang_Nhap.tkDangnhap.getUsername());
//        Calendar calendar = Calendar.getInstance(Locale.forLanguageTag("VN"));               
//        String idDb = "HD"+LocalDateTime.now().getNano();
//        lbMahd.setText(idDb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnDrinks = new com.k33ptoo.components.KButton();
        btnCake = new com.k33ptoo.components.KButton();
        txtTimkiem = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        kTTHD = new com.k33ptoo.components.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnMangdi = new com.k33ptoo.components.KButton();
        btnTaicho = new com.k33ptoo.components.KButton();
        btnCong = new com.k33ptoo.components.KButton();
        lbSoluong = new javax.swing.JLabel();
        btnTru = new com.k33ptoo.components.KButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnThanhtoan = new com.k33ptoo.components.KButton();
        btnHuy = new com.k33ptoo.components.KButton();
        lbMahd = new javax.swing.JLabel();
        lbManv = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnThemmon = new com.k33ptoo.components.KButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtKhachhang = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnCTHD = new com.k33ptoo.components.KButton();
        lbTongtien = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        pnThucdon = new javax.swing.JPanel();
        btnTimkiem6 = new com.k33ptoo.components.KButton();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        kButton9 = new com.k33ptoo.components.KButton();
        lbStatics1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnStatics1 = new com.k33ptoo.components.KButton();
        lbAccount1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnAccount1 = new com.k33ptoo.components.KButton();
        lbDashboard1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnLogout1 = new com.k33ptoo.components.KButton();
        lbManagement1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnManagement1 = new com.k33ptoo.components.KButton();
        lbOrder1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnOrder1 = new com.k33ptoo.components.KButton();
        lbWorkbench1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnWorkbench1 = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Cake");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 50, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Drinks");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 50, 20));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel25.setText("Order");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 210, 50));

        btnDrinks.setkBorderRadius(25);
        btnDrinks.setkEndColor(new java.awt.Color(255, 153, 255));
        btnDrinks.setkHoverEndColor(new java.awt.Color(255, 153, 51));
        btnDrinks.setkHoverForeGround(new java.awt.Color(255, 102, 102));
        btnDrinks.setkHoverStartColor(new java.awt.Color(255, 204, 102));
        btnDrinks.setkStartColor(new java.awt.Color(255, 255, 153));
        jPanel1.add(btnDrinks, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 130, 40));

        btnCake.setkBorderRadius(25);
        btnCake.setkEndColor(new java.awt.Color(102, 204, 255));
        btnCake.setkHoverEndColor(new java.awt.Color(255, 102, 153));
        btnCake.setkHoverForeGround(new java.awt.Color(204, 102, 255));
        btnCake.setkHoverStartColor(new java.awt.Color(255, 102, 255));
        btnCake.setkStartColor(new java.awt.Color(255, 204, 255));
        jPanel1.add(btnCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 150, 40));

        txtTimkiem.setOpaque(false);
        jPanel1.add(txtTimkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 490, 40));
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 30, 30));

        kTTHD.setBackground(new java.awt.Color(255, 255, 255));
        kTTHD.setkBorderRadius(35);
        kTTHD.setkEndColor(new java.awt.Color(204, 204, 255));
        kTTHD.setkStartColor(new java.awt.Color(255, 153, 255));
        kTTHD.setOpaque(false);
        kTTHD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tại chỗ");
        kTTHD.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 120, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mang đi");
        kTTHD.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 120, 30));

        btnMangdi.setToolTipText("");
        btnMangdi.setkBackGroundColor(new java.awt.Color(0, 204, 153));
        btnMangdi.setkBorderRadius(25);
        btnMangdi.setkEndColor(new java.awt.Color(0, 255, 102));
        btnMangdi.setkHoverEndColor(new java.awt.Color(255, 153, 51));
        btnMangdi.setkHoverForeGround(new java.awt.Color(255, 102, 102));
        btnMangdi.setkHoverStartColor(new java.awt.Color(255, 51, 51));
        btnMangdi.setkStartColor(new java.awt.Color(0, 204, 204));
        btnMangdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMangdiActionPerformed(evt);
            }
        });
        kTTHD.add(btnMangdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 50));

        btnTaicho.setToolTipText("");
        btnTaicho.setkBorderRadius(25);
        btnTaicho.setkEndColor(new java.awt.Color(102, 0, 102));
        btnTaicho.setkHoverEndColor(new java.awt.Color(255, 153, 51));
        btnTaicho.setkHoverForeGround(new java.awt.Color(255, 102, 102));
        btnTaicho.setkHoverStartColor(new java.awt.Color(255, 51, 51));
        btnTaicho.setkStartColor(new java.awt.Color(0, 255, 153));
        btnTaicho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaichoActionPerformed(evt);
            }
        });
        kTTHD.add(btnTaicho, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 120, 50));

        btnCong.setForeground(new java.awt.Color(51, 51, 51));
        btnCong.setText("+");
        btnCong.setToolTipText("");
        btnCong.setkBorderRadius(50);
        btnCong.setkEndColor(new java.awt.Color(102, 0, 102));
        btnCong.setkHoverEndColor(new java.awt.Color(255, 153, 51));
        btnCong.setkHoverForeGround(new java.awt.Color(255, 102, 102));
        btnCong.setkHoverStartColor(new java.awt.Color(255, 51, 51));
        btnCong.setkStartColor(new java.awt.Color(255, 102, 0));
        btnCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongActionPerformed(evt);
            }
        });
        kTTHD.add(btnCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 35, 35));

        lbSoluong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbSoluong.setText("0");
        kTTHD.add(lbSoluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, 35));

        btnTru.setText("-");
        btnTru.setToolTipText("");
        btnTru.setkBorderRadius(50);
        btnTru.setkEndColor(new java.awt.Color(102, 0, 102));
        btnTru.setkHoverEndColor(new java.awt.Color(255, 153, 51));
        btnTru.setkHoverForeGround(new java.awt.Color(255, 102, 102));
        btnTru.setkHoverStartColor(new java.awt.Color(255, 51, 51));
        btnTru.setkStartColor(new java.awt.Color(255, 102, 0));
        btnTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruActionPerformed(evt);
            }
        });
        kTTHD.add(btnTru, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 35, 35));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Thanh toán");
        kTTHD.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 90, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Hủy");
        kTTHD.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 620, 90, 20));

        btnThanhtoan.setToolTipText("");
        btnThanhtoan.setkBorderRadius(25);
        btnThanhtoan.setkEndColor(new java.awt.Color(102, 0, 102));
        btnThanhtoan.setkHoverEndColor(new java.awt.Color(255, 153, 51));
        btnThanhtoan.setkHoverForeGround(new java.awt.Color(255, 102, 102));
        btnThanhtoan.setkHoverStartColor(new java.awt.Color(255, 51, 51));
        btnThanhtoan.setkStartColor(new java.awt.Color(0, 255, 51));
        btnThanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhtoanActionPerformed(evt);
            }
        });
        kTTHD.add(btnThanhtoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 110, 40));

        btnHuy.setToolTipText("");
        btnHuy.setkBorderRadius(25);
        btnHuy.setkEndColor(new java.awt.Color(102, 0, 102));
        btnHuy.setkHoverEndColor(new java.awt.Color(255, 153, 51));
        btnHuy.setkHoverForeGround(new java.awt.Color(255, 102, 102));
        btnHuy.setkHoverStartColor(new java.awt.Color(255, 51, 51));
        btnHuy.setkStartColor(new java.awt.Color(0, 204, 51));
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        kTTHD.add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 610, 110, 40));

        lbMahd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMahd.setForeground(new java.awt.Color(255, 255, 255));
        lbMahd.setText("MAHD");
        kTTHD.add(lbMahd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 150, 35));

        lbManv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbManv.setForeground(new java.awt.Color(255, 255, 255));
        lbManv.setText("MANV");
        kTTHD.add(lbManv, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 240, 35));

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Order");
        kTTHD.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 100, 40));

        btnThemmon.setToolTipText("");
        btnThemmon.setkBorderRadius(25);
        btnThemmon.setkEndColor(new java.awt.Color(102, 0, 102));
        btnThemmon.setkHoverEndColor(new java.awt.Color(255, 153, 51));
        btnThemmon.setkHoverForeGround(new java.awt.Color(255, 102, 102));
        btnThemmon.setkHoverStartColor(new java.awt.Color(255, 51, 51));
        btnThemmon.setkStartColor(new java.awt.Color(51, 204, 255));
        btnThemmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemmonActionPerformed(evt);
            }
        });
        kTTHD.add(btnThemmon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 120, 40));
        kTTHD.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 260, 10));

        txtKhachhang.setBackground(new java.awt.Color(255, 153, 255));
        txtKhachhang.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txtKhachhang.setForeground(new java.awt.Color(255, 255, 255));
        txtKhachhang.setBorder(null);
        txtKhachhang.setOpaque(false);
        txtKhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtKhachhangMouseClicked(evt);
            }
        });
        kTTHD.add(txtKhachhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 260, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("CTHD");
        kTTHD.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 100, 40));

        btnCTHD.setkBorderRadius(25);
        btnCTHD.setkEndColor(new java.awt.Color(255, 153, 255));
        btnCTHD.setkHoverEndColor(new java.awt.Color(255, 153, 51));
        btnCTHD.setkHoverForeGround(new java.awt.Color(255, 102, 102));
        btnCTHD.setkHoverStartColor(new java.awt.Color(255, 204, 102));
        btnCTHD.setkStartColor(new java.awt.Color(255, 255, 153));
        btnCTHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTHDActionPerformed(evt);
            }
        });
        kTTHD.add(btnCTHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 120, 40));

        lbTongtien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTongtien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTongtien.setText("Tổng tiền");
        kTTHD.add(lbTongtien, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, 150, -1));

        jPanel1.add(kTTHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 70, 280, 690));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Tìm kiếm");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, 90, 40));

        pnThucdon.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnThucdonLayout = new javax.swing.GroupLayout(pnThucdon);
        pnThucdon.setLayout(pnThucdonLayout);
        pnThucdonLayout.setHorizontalGroup(
            pnThucdonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        pnThucdonLayout.setVerticalGroup(
            pnThucdonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jPanel1.add(pnThucdon, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 650, 530));

        btnTimkiem6.setToolTipText("");
        btnTimkiem6.setkBorderRadius(25);
        btnTimkiem6.setkEndColor(new java.awt.Color(102, 0, 102));
        btnTimkiem6.setkHoverEndColor(new java.awt.Color(255, 153, 51));
        btnTimkiem6.setkHoverForeGround(new java.awt.Color(255, 102, 102));
        btnTimkiem6.setkHoverStartColor(new java.awt.Color(255, 51, 51));
        btnTimkiem6.setkStartColor(new java.awt.Color(51, 204, 255));
        btnTimkiem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiem6ActionPerformed(evt);
            }
        });
        jPanel1.add(btnTimkiem6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 150, 110, 40));

        kGradientPanel2.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkBorderRadius(50);
        kGradientPanel2.setkEndColor(new java.awt.Color(204, 153, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(204, 153, 255));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton9.setkBorderRadius(15);
        kButton9.setkEndColor(new java.awt.Color(0, 255, 204));
        kButton9.setkHoverEndColor(new java.awt.Color(153, 51, 255));
        kButton9.setkHoverForeGround(new java.awt.Color(204, 102, 255));
        kButton9.setkHoverStartColor(new java.awt.Color(204, 102, 255));
        kGradientPanel2.add(kButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 150, 210));

        lbStatics1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbStatics1.setForeground(new java.awt.Color(255, 255, 255));
        lbStatics1.setText("Statistics");
        kGradientPanel2.add(lbStatics1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 120, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\vomin\\OneDrive\\Máy tính\\icons8-account-18.png")); // NOI18N
        kGradientPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 30, 50));

        btnStatics1.setkBorderRadius(0);
        btnStatics1.setkEndColor(new java.awt.Color(204, 153, 255));
        btnStatics1.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        btnStatics1.setkHoverForeGround(new java.awt.Color(255, 102, 255));
        btnStatics1.setkHoverStartColor(new java.awt.Color(255, 153, 255));
        btnStatics1.setkStartColor(new java.awt.Color(204, 153, 255));
        btnStatics1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatics1ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnStatics1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 210, 50));

        lbAccount1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbAccount1.setForeground(new java.awt.Color(255, 255, 255));
        lbAccount1.setText("Account");
        kGradientPanel2.add(lbAccount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 120, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\vomin\\OneDrive\\Máy tính\\icons8-user-account-18.png")); // NOI18N
        kGradientPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 30, 50));

        btnAccount1.setkBorderRadius(0);
        btnAccount1.setkEndColor(new java.awt.Color(204, 153, 255));
        btnAccount1.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        btnAccount1.setkHoverForeGround(new java.awt.Color(255, 102, 255));
        btnAccount1.setkHoverStartColor(new java.awt.Color(255, 163, 255));
        btnAccount1.setkStartColor(new java.awt.Color(204, 153, 255));
        btnAccount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccount1ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnAccount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 210, 50));

        lbDashboard1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbDashboard1.setForeground(new java.awt.Color(255, 255, 255));
        lbDashboard1.setText("Log out");
        kGradientPanel2.add(lbDashboard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 120, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\vomin\\Downloads\\icons8-logout-rounded-left-24.png")); // NOI18N
        kGradientPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 30, 50));

        btnLogout1.setkBorderRadius(0);
        btnLogout1.setkEndColor(new java.awt.Color(204, 153, 255));
        btnLogout1.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        btnLogout1.setkHoverForeGround(new java.awt.Color(255, 102, 255));
        btnLogout1.setkHoverStartColor(new java.awt.Color(255, 153, 255));
        btnLogout1.setkStartColor(new java.awt.Color(204, 153, 255));
        btnLogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout1ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnLogout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 210, 50));

        lbManagement1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbManagement1.setForeground(new java.awt.Color(255, 255, 255));
        lbManagement1.setText("Management");
        kGradientPanel2.add(lbManagement1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 120, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\vomin\\OneDrive\\Máy tính\\icons8-add-user-male-18.png")); // NOI18N
        kGradientPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 30, 50));

        btnManagement1.setkBorderRadius(0);
        btnManagement1.setkEndColor(new java.awt.Color(204, 153, 255));
        btnManagement1.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        btnManagement1.setkHoverForeGround(new java.awt.Color(255, 102, 255));
        btnManagement1.setkHoverStartColor(new java.awt.Color(255, 153, 255));
        btnManagement1.setkStartColor(new java.awt.Color(204, 153, 255));
        btnManagement1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagement1ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnManagement1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 210, 50));

        lbOrder1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbOrder1.setForeground(new java.awt.Color(255, 255, 255));
        lbOrder1.setText("Order");
        kGradientPanel2.add(lbOrder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 120, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\vomin\\OneDrive\\Máy tính\\icons8-shopping-cart-18.png")); // NOI18N
        kGradientPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 30, 50));

        btnOrder1.setkBorderRadius(0);
        btnOrder1.setkEndColor(new java.awt.Color(204, 153, 255));
        btnOrder1.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        btnOrder1.setkHoverForeGround(new java.awt.Color(255, 102, 204));
        btnOrder1.setkHoverStartColor(new java.awt.Color(255, 153, 255));
        btnOrder1.setkStartColor(new java.awt.Color(204, 153, 255));
        btnOrder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrder1ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnOrder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 210, 50));

        lbWorkbench1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbWorkbench1.setForeground(new java.awt.Color(255, 255, 255));
        lbWorkbench1.setText("Workbench");
        kGradientPanel2.add(lbWorkbench1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 120, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\vomin\\OneDrive\\Máy tính\\icons8-home-18.png")); // NOI18N
        kGradientPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 30, 50));

        btnWorkbench1.setkBorderRadius(0);
        btnWorkbench1.setkEndColor(new java.awt.Color(204, 153, 255));
        btnWorkbench1.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        btnWorkbench1.setkHoverForeGround(new java.awt.Color(255, 102, 255));
        btnWorkbench1.setkHoverStartColor(new java.awt.Color(255, 153, 255));
        btnWorkbench1.setkStartColor(new java.awt.Color(204, 153, 255));
        btnWorkbench1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkbench1ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnWorkbench1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 210, 50));

        jPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 250, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1427, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void setIDHDAuto(){
        Calendar calendar = Calendar.getInstance(Locale.forLanguageTag("VN"));               
        String idDb = "HD"+LocalDateTime.now().getNano();
        lbMahd.setText(idDb);
    }
    
    ArrayList<ThucDon> thucDons = new ArrayList<>();    
    ArrayList<ChiTietHoaDon> cthds = new ArrayList<>(); 
    private void fillDataBill(){
        String ttd = "", sl = "", gt = "", tt = "";
        cthds = new ChiTietHoaDonDAO().timtheoIDfix(cthd.getMahd());
            for (ChiTietHoaDon item : cthds) { 
                ThucDon tdtk = new ThucDonDAO().timkiemtheoID(item.getMatd());
                ttd += tdtk.getTentd()+",";
                sl += item.getSoluong()+" ";
                gt += item.getDongia()+" ";
                tt += item.getThanhtien()+" ";
            }
//            lbTTD.setText(ttd);
//            lbSLTD.setText(sl);
//            lbDGTD.setText(gt);
//            lbTTTD.setText(tt);    
    }
    
        private void fillDataBillFIX(){
        cthds = new ChiTietHoaDonDAO().timtheoIDfix(cthd.getMahd());
        int x = 20;
        int y = 310;
        JLabel lbttd = new JLabel();
        JLabel lbtsl = new JLabel();
        JLabel lbtgt = new JLabel();
        JLabel lbttt = new JLabel();
        
        lbttd.setBounds(20, 330, 160, 30);
        lbttd.setText("Tên thực đơn");
        lbttd.setFont(new Font("Tahoma", Font.BOLD, 13));
        
        lbtsl.setBounds(20+100, 330, 160, 30);
        lbtsl.setText("SL");
        lbtsl.setFont(new Font("Tahoma", Font.BOLD, 13));
        
        lbtgt.setBounds(20+150, 330, 160, 30);
        lbtgt.setText("ĐG");
        lbtgt.setFont(new Font("Tahoma", Font.BOLD, 13));

        lbttt.setBounds(20+210, 330, 260, 30);
        lbttt.setText("TT");
        lbttt.setFont(new Font("Tahoma", Font.BOLD, 13));        
            for (ChiTietHoaDon item : cthds) { 
                y+=50;
                ThucDon tdtk = new ThucDonDAO().timkiemtheoID(item.getMatd()); 
//                JLabel labelItem = new JLabel();
                JLabel labelttd = new JLabel();
                JLabel labelsl = new JLabel();
                JLabel labelgt = new JLabel();
                JLabel labeltt = new JLabel();
                labelgt.setVisible(true);
                labelsl.setVisible(true);
                labeltt.setVisible(true);
                labelttd.setVisible(true);
                labelttd.setBounds(x, y, 160, 50);
                labelsl.setBounds(x+100, y, 160, 50);
                labelgt.setBounds(x+150, y, 160, 50);
                labeltt.setBounds(x+200, y, 160, 50);
                
                labelttd.setText(tdtk.getTentd());
                labelsl.setText(String.valueOf(item.getSoluong()));
                labelgt.setText(String.valueOf(item.getDongia()));
                labeltt.setText(String.valueOf(item.getThanhtien()));               
            this.kTTHD.setLayout(null);
            this.kTTHD.add(lbttd);
            this.kTTHD.add(lbtgt);
            this.kTTHD.add(lbtsl);
            this.kTTHD.add(lbttt);
            this.kTTHD.add(lbttd);
            this.kTTHD.add(lbttd);
            this.kTTHD.add(labelttd);
            this.kTTHD.add(labelgt);
            this.kTTHD.add(labelsl);
            this.kTTHD.add(labeltt);
            }    
        Locale localeVN = new Locale("vi", "VN");
        NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);
        float tongtien = new ChiTietHoaDonDAO().tongtienhoadon(lbMahd.getText());
        lbTongtien.setText(currencyVN.format(tongtien));
    }
    
    private void btnTimkiem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimkiem6ActionPerformed

    private void txtKhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKhachhangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKhachhangMouseClicked

    private void btnThemmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemmonActionPerformed
        // TODO add your handling code here:
        if(lbSoluong.getText().equals("0"))
        JOptionPane.showMessageDialog(rootPane, "Chưa chọn số lượng cho thực đơn");
        else{
            cthd.setSoluong(Integer.parseInt(lbSoluong.getText()));
            cthd.setSoluong(Integer.parseInt(String.valueOf(lbSoluong.getText())));
            cthd.setGiamgia(1);
            cthd.setThanhtien(cthd.getSoluong()*cthd.getDongia()*cthd.getGiamgia());
            new ChiTietHoaDonDAO().them(cthd);

//            fillDataBillFIX();
        }
    }//GEN-LAST:event_btnThemmonActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        new ChiTietHoaDonDAO().xoaHoaDonALL(lbMahd.getText());
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnThanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhtoanActionPerformed
        // TODO add your handling code here:
        hd.setMahd(lbMahd.getText());
        hd.setManv(Dang_Nhap.tkDangnhap.getManv());
        java.sql.Date ngayban = new java.sql.Date(System.currentTimeMillis());
        hd.setNgayban(ngayban);
        KhachHang ttKh = new KhachHangDAO().timkiemtheoID(txtKhachhang.getText());
        if(txtKhachhang.getText().equals(""))
        JOptionPane.showMessageDialog(rootPane, "Chưa có thông tin khách hàng");
        else{
            if(ttKh!=null)
            hd.setMakh(ttKh.getHoten());
            else
            hd.setMakh(txtKhachhang.getText());
            hd.setTongtien(new ChiTietHoaDonDAO().tongtienhoadon(hd.getMahd()));
            System.out.println(""+hd.toString());
            new HoaDonDAO().them(hd);
            JOptionPane.showMessageDialog(rootPane, "Thêm hóa đơn thành công");
            setIDHDAuto();
        }
    }//GEN-LAST:event_btnThanhtoanActionPerformed

    private void btnTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruActionPerformed
        // TODO add your handling code here:
        if(!lbSoluong.getText().equals("0")){
            lbSoluong.setText(String.valueOf(Integer.parseInt(lbSoluong.getText())-1));
        }
        else{
            lbSoluong.setText("0");
        }

    }//GEN-LAST:event_btnTruActionPerformed

    private void btnCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongActionPerformed
        // TODO add your handling code here:
        if(!lbSoluong.getText().equals("0")){
            lbSoluong.setText(String.valueOf(Integer.parseInt(lbSoluong.getText())+1));
            cthd.setSoluong(Integer.parseInt(String.valueOf(lbSoluong.getText())));
            cthd.setGiamgia(1);
            cthd.setThanhtien(cthd.getSoluong()*cthd.getDongia()*cthd.getGiamgia());
        }else{
            lbSoluong.setText(String.valueOf(Integer.parseInt(lbSoluong.getText())+1));
        }
    }//GEN-LAST:event_btnCongActionPerformed

    private void btnTaichoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaichoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTaichoActionPerformed

    private void btnMangdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMangdiActionPerformed
        // TODO add your handling code here:
        ThucDonDAO tdDAO = new ThucDonDAO();
        thucDons.clear();
        try {
            thucDons = tdDAO.timkiemThucDons(txtTimkiem.getText());

            showListFood();
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnMangdiActionPerformed

    private void btnCTHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCTHDActionPerformed
        // TODO add your handling code here:
        this.kTTHD.revalidate();
        this.kTTHD.repaint();
        fillDataBillFIX();
    }//GEN-LAST:event_btnCTHDActionPerformed

    private void btnStaticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaticsActionPerformed
        // TODO add your handling code here:
        new StaticsFormChoose().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStaticsActionPerformed

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        // TODO add your handling code here:
        new TTCaNhan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAccountActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new Dang_Nhap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagementActionPerformed
        // TODO add your handling code here:
        new MagementForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManagementActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // TODO add your handling code here:
        new OrderFormChoose().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnWorkbenchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkbenchActionPerformed
        // TODO add your handling code here:
        new Welecome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnWorkbenchActionPerformed

    private void btnStatics1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatics1ActionPerformed
        // TODO add your handling code here:
        new StaticsFormChoose().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStatics1ActionPerformed

    private void btnAccount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccount1ActionPerformed
        // TODO add your handling code here:
        new TTCaNhan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAccount1ActionPerformed

    private void btnLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout1ActionPerformed
        // TODO add your handling code here:
        new Dang_Nhap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogout1ActionPerformed

    private void btnManagement1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagement1ActionPerformed
        // TODO add your handling code here:
        new MagementForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManagement1ActionPerformed

    private void btnOrder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrder1ActionPerformed
        // TODO add your handling code here:
        new OrderFormChoose().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOrder1ActionPerformed

    private void btnWorkbench1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkbench1ActionPerformed
        // TODO add your handling code here:
        new Welecome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnWorkbench1ActionPerformed

    
    ChiTietHoaDon cthd = new ChiTietHoaDon();
    HoaDon hd = new HoaDon();
    private void showListFood(){
        thucDons = new ThucDonDAO().toanbodanhsach();             
        int dem = 0;
        int gtdong = 0;
        if(thucDons.size()/2-1<=1){
            gtdong = thucDons.size()/2;
        }else
            gtdong = thucDons.size()/2-1;      
          int x = 10;
          int y = 10;
          int count = 0;
        for (ThucDon td : thucDons) {       
                JLabel label = new JLabel();
                label.setOpaque(true);
                label.setBackground(Color.WHITE);
                label.setHorizontalAlignment(JLabel.CENTER);
                label.setVerticalAlignment(JLabel.CENTER);
                label.setHorizontalTextPosition(JLabel.CENTER);
                label.setVerticalTextPosition(JLabel.BOTTOM);
                //label.setBorder(new LineBorder(Color.BLACK));
                ImageIcon imageIcon = new ImageIcon(td.getAnh());
                Image image = imageIcon.getImage();
                Image newimg = image.getScaledInstance(130, 120,  java.awt.Image.SCALE_SMOOTH);
                imageIcon = new ImageIcon(newimg);
                label.setIcon(imageIcon);
                label.setFont(new Font("Tahoma", Font.BOLD, 13));
                label.setForeground(Color.darkGray);
                label.setText(td.getTentd());
                count++;
                //label.setSize(160, 150);
                if(count>2 && count%2==0){
                    y+=200;
                    x=10;
                    label.setBounds(x, y, 160, 150);
                }
                else
                    label.setBounds(x, y, 160, 150);
                x+=200;  
                label.addMouseListener(new MouseAdapter() {
                    public void mouseClicked(MouseEvent event){                                                                      
                        try {                           
//                        cthd = new ChiTietHoaDon();
                        cthd.setMahd(lbMahd.getText());
                            if(label.getBackground()==Color.WHITE){                                
                                label.setBackground(Color.CYAN);
                                cthd.setMatd(td.getMatd());                                
                                cthd.setDongia(td.getDongiaban());                               
                            }                           
                            else if(label.getBackground()==Color.CYAN){
                                label.setBackground(Color.WHITE);
                                new ChiTietHoaDonDAO().xoaFIX(lbMahd.getText(),td.getMatd());
                                //fillDataBill();
                                fillDataBillFIX();
                            }                                                       
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                        System.out.println(""+cthds.size());
                    }

                });                               
                this.pnThucdon.setLayout(null);                
                this.pnThucdon.add(label);
                
            }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnAccount;
    private com.k33ptoo.components.KButton btnAccount1;
    private com.k33ptoo.components.KButton btnCTHD;
    private com.k33ptoo.components.KButton btnCake;
    private com.k33ptoo.components.KButton btnCong;
    private com.k33ptoo.components.KButton btnDrinks;
    private com.k33ptoo.components.KButton btnHuy;
    private com.k33ptoo.components.KButton btnLogout;
    private com.k33ptoo.components.KButton btnLogout1;
    private com.k33ptoo.components.KButton btnManagement;
    private com.k33ptoo.components.KButton btnManagement1;
    private com.k33ptoo.components.KButton btnMangdi;
    private com.k33ptoo.components.KButton btnOrder;
    private com.k33ptoo.components.KButton btnOrder1;
    private com.k33ptoo.components.KButton btnStatics;
    private com.k33ptoo.components.KButton btnStatics1;
    private com.k33ptoo.components.KButton btnTaicho;
    private com.k33ptoo.components.KButton btnThanhtoan;
    private com.k33ptoo.components.KButton btnThemmon;
    private com.k33ptoo.components.KButton btnTimkiem6;
    private com.k33ptoo.components.KButton btnTru;
    private com.k33ptoo.components.KButton btnWorkbench;
    private com.k33ptoo.components.KButton btnWorkbench1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private com.k33ptoo.components.KButton kButton8;
    private com.k33ptoo.components.KButton kButton9;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private com.k33ptoo.components.KGradientPanel kTTHD;
    private javax.swing.JLabel lbAccount;
    private javax.swing.JLabel lbAccount1;
    private javax.swing.JLabel lbDashboard;
    private javax.swing.JLabel lbDashboard1;
    private javax.swing.JLabel lbMahd;
    private javax.swing.JLabel lbManagement;
    private javax.swing.JLabel lbManagement1;
    private javax.swing.JLabel lbManv;
    private javax.swing.JLabel lbOrder;
    private javax.swing.JLabel lbOrder1;
    private javax.swing.JLabel lbSoluong;
    private javax.swing.JLabel lbStatics;
    private javax.swing.JLabel lbStatics1;
    private javax.swing.JLabel lbTongtien;
    private javax.swing.JLabel lbWorkbench;
    private javax.swing.JLabel lbWorkbench1;
    private javax.swing.JPanel pnThucdon;
    private javax.swing.JTextField txtKhachhang;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables
}
