/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLiTaiKhoan;

import DAO.NhanVienDAO;
import DAO.TaiKhoanDAO;
import Model.NhanVien;
import TrangChinh.Dang_Nhap;
import TrangChinh.MagementForm;
import TrangChinh.OrderFormChoose;
import TrangChinh.StaticsFormChoose;
import TrangChinh.Welecome;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class TTCaNhan extends javax.swing.JFrame {

    /**
     * Creates new form TTcanhan
     */
    public TTCaNhan() {
        initComponents();
        fillInformation();
    }

    private void fillInformation(){
        try {
        NhanVien nv = new NhanVienDAO().timkiemtheoID(Dang_Nhap.tkDangnhap.getManv());
//        ImageIcon imageIcon = new ImageIcon(nv.getAnh());
//        Image image = imageIcon.getImage();
//        Image newimg = image.getScaledInstance(220, 240,  java.awt.Image.SCALE_SMOOTH);
//        imageIcon = new ImageIcon(newimg);
//        lbAnh.setIcon((Icon) newimg);
        lbChucvu.setText(lbChucvu.getText()+": "+nv.getChucvu());
        lbDiachi.setText(lbDiachi.getText()+": "+nv.getDiachi());
        lbGioitinh.setText(lbGioitinh.getText()+": "+nv.getGioitinh());
        lbHoten.setText(lbHoten.getText()+": "+nv.getTennv());
        lbID.setText(lbID.getText()+": "+nv.getIdcanhan());
        lbManv.setText(lbManv.getText()+": "+nv.getManv());
        lbNgaysinh.setText(lbNgaysinh.getText()+": "+String.valueOf(nv.getNgaysinh()));
        lbSdt.setText(lbSdt.getText()+": "+nv.getSdt());            
        } catch (Exception e) {
        }


    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        btnReset = new com.k33ptoo.components.KButton();
        btnThoat = new com.k33ptoo.components.KButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel36 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbHoten = new javax.swing.JLabel();
        kButton11 = new com.k33ptoo.components.KButton();
        jLabel26 = new javax.swing.JLabel();
        kButton13 = new com.k33ptoo.components.KButton();
        jLabel27 = new javax.swing.JLabel();
        kButton14 = new com.k33ptoo.components.KButton();
        jLabel20 = new javax.swing.JLabel();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        lbChucvu = new javax.swing.JLabel();
        lbAnh = new javax.swing.JLabel();
        lbManv = new javax.swing.JLabel();
        lbGioitinh = new javax.swing.JLabel();
        lbSdt = new javax.swing.JLabel();
        lbDiachi = new javax.swing.JLabel();
        lbID = new javax.swing.JLabel();
        lbNgaysinh = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pwfCu = new javax.swing.JPasswordField();
        pwfMoi = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        pwfNhaplai = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        kButton8 = new com.k33ptoo.components.KButton();
        lbStatics = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnStatics = new com.k33ptoo.components.KButton();
        lbAccount = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnAccount = new com.k33ptoo.components.KButton();
        lbDashboard = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnLogout = new com.k33ptoo.components.KButton();
        lbManagement = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnManagement = new com.k33ptoo.components.KButton();
        lbOrder = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnOrder = new com.k33ptoo.components.KButton();
        lbWorkbench = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnWorkbench = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("CANCEL");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 690, 120, 45));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("RESET PASSWORD");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 690, 120, 45));

        btnReset.setkBackGroundColor(new java.awt.Color(0, 255, 153));
        btnReset.setkBorderRadius(0);
        btnReset.setkEndColor(new java.awt.Color(153, 153, 255));
        btnReset.setkHoverEndColor(new java.awt.Color(204, 102, 255));
        btnReset.setkHoverForeGround(new java.awt.Color(153, 153, 255));
        btnReset.setkHoverStartColor(new java.awt.Color(255, 153, 255));
        btnReset.setkSelectedColor(new java.awt.Color(0, 153, 153));
        btnReset.setkStartColor(new java.awt.Color(102, 102, 255));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 690, 140, 45));

        btnThoat.setkBackGroundColor(new java.awt.Color(0, 255, 153));
        btnThoat.setkBorderRadius(0);
        btnThoat.setkEndColor(new java.awt.Color(153, 153, 255));
        btnThoat.setkHoverEndColor(new java.awt.Color(204, 102, 255));
        btnThoat.setkHoverForeGround(new java.awt.Color(153, 153, 255));
        btnThoat.setkHoverStartColor(new java.awt.Color(255, 153, 255));
        btnThoat.setkSelectedColor(new java.awt.Color(0, 153, 153));
        btnThoat.setkStartColor(new java.awt.Color(102, 102, 255));
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel1.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 690, 140, 45));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 590, 380, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 670, 380, 20));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 51, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Reset Password ?");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 570, 40));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Update");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 70, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Clear");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 50, 50, 20));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel25.setText("My Account");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 360, 50));

        jLabel13.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Thay đổi mật khẩu");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 570, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        lbHoten.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbHoten.setText("Họ và tên");
        jPanel1.add(lbHoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, 20));

        kButton11.setkBackGroundColor(new java.awt.Color(0, 153, 255));
        kButton11.setkBorderRadius(0);
        kButton11.setkEndColor(new java.awt.Color(102, 204, 255));
        kButton11.setkHoverEndColor(new java.awt.Color(255, 153, 153));
        kButton11.setkHoverForeGround(new java.awt.Color(204, 102, 255));
        kButton11.setkHoverStartColor(new java.awt.Color(255, 153, 153));
        kButton11.setkPressedColor(new java.awt.Color(153, 153, 255));
        kButton11.setkSelectedColor(new java.awt.Color(153, 102, 255));
        kButton11.setkStartColor(new java.awt.Color(204, 153, 255));
        jPanel1.add(kButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 140, 40));

        jLabel26.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("Thông tin cá nhân");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        kButton13.setkBackGroundColor(new java.awt.Color(0, 153, 255));
        kButton13.setkBorderRadius(0);
        kButton13.setkEndColor(new java.awt.Color(102, 204, 255));
        kButton13.setkHoverEndColor(new java.awt.Color(255, 153, 153));
        kButton13.setkHoverForeGround(new java.awt.Color(204, 102, 255));
        kButton13.setkHoverStartColor(new java.awt.Color(255, 153, 153));
        kButton13.setkPressedColor(new java.awt.Color(153, 153, 255));
        kButton13.setkSelectedColor(new java.awt.Color(153, 102, 255));
        kButton13.setkStartColor(new java.awt.Color(204, 153, 255));
        jPanel1.add(kButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 40, 140, 40));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Liên hệ KTV");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 50, 100, 20));

        kButton14.setkBackGroundColor(new java.awt.Color(0, 153, 255));
        kButton14.setkBorderRadius(0);
        kButton14.setkEndColor(new java.awt.Color(102, 204, 255));
        kButton14.setkHoverEndColor(new java.awt.Color(255, 153, 153));
        kButton14.setkHoverForeGround(new java.awt.Color(204, 102, 255));
        kButton14.setkHoverStartColor(new java.awt.Color(255, 153, 153));
        kButton14.setkPressedColor(new java.awt.Color(153, 153, 255));
        kButton14.setkSelectedColor(new java.awt.Color(153, 102, 255));
        kButton14.setkStartColor(new java.awt.Color(204, 153, 255));
        jPanel1.add(kButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 40, 140, 40));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Quay lại");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 280, 70, 20));

        kGradientPanel2.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(153, 204, 255));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbChucvu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbChucvu.setText("Nhân viên quản lý");
        kGradientPanel2.add(lbChucvu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 150, 40));
        kGradientPanel2.add(lbAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 240));

        jPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 220, 320));

        lbManv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbManv.setText("Mã nhân viên");
        jPanel1.add(lbManv, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, -1, 20));

        lbGioitinh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbGioitinh.setText("Giới tính");
        jPanel1.add(lbGioitinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, -1, 20));

        lbSdt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSdt.setText("Số điện thoại");
        jPanel1.add(lbSdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, -1, 20));

        lbDiachi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDiachi.setText("Địa chỉ");
        jPanel1.add(lbDiachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 130, -1, 20));

        lbID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbID.setText("CCCD/CMND");
        jPanel1.add(lbID, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 180, -1, 20));

        lbNgaysinh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNgaysinh.setText("Ngày sinh");
        jPanel1.add(lbNgaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 230, -1, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 204));
        jLabel16.setText("Mật khẩu mới");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 540, 380, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 204));
        jLabel17.setText("Mật khẩu cũ");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 380, -1));
        jLabel17.getAccessibleContext().setAccessibleName("Mật khẩu mới");

        pwfCu.setText("passcu");
        pwfCu.setBorder(null);
        jPanel1.add(pwfCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 380, 30));

        pwfMoi.setBorder(null);
        jPanel1.add(pwfMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 560, 380, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 204));
        jLabel18.setText("Nhập lại mật khẩu");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 620, -1, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, 380, 10));

        pwfNhaplai.setBorder(null);
        jPanel1.add(pwfNhaplai, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 640, 380, 30));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setOpaque(true);
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 590, 350));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, -1, -1));

        kGradientPanel1.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkBorderRadius(50);
        kGradientPanel1.setkEndColor(new java.awt.Color(204, 153, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 153, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton8.setkBorderRadius(15);
        kButton8.setkEndColor(new java.awt.Color(0, 255, 204));
        kButton8.setkHoverEndColor(new java.awt.Color(153, 51, 255));
        kButton8.setkHoverForeGround(new java.awt.Color(204, 102, 255));
        kButton8.setkHoverStartColor(new java.awt.Color(204, 102, 255));
        kGradientPanel1.add(kButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 150, 210));

        lbStatics.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbStatics.setForeground(new java.awt.Color(255, 255, 255));
        lbStatics.setText("Statistics");
        kGradientPanel1.add(lbStatics, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 120, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\vomin\\OneDrive\\Máy tính\\icons8-account-18.png")); // NOI18N
        kGradientPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 30, 50));

        btnStatics.setkBorderRadius(0);
        btnStatics.setkEndColor(new java.awt.Color(204, 153, 255));
        btnStatics.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        btnStatics.setkHoverForeGround(new java.awt.Color(255, 102, 255));
        btnStatics.setkHoverStartColor(new java.awt.Color(255, 153, 255));
        btnStatics.setkStartColor(new java.awt.Color(204, 153, 255));
        btnStatics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaticsActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnStatics, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 210, 50));

        lbAccount.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbAccount.setForeground(new java.awt.Color(255, 255, 255));
        lbAccount.setText("Account");
        kGradientPanel1.add(lbAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 120, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\vomin\\OneDrive\\Máy tính\\icons8-user-account-18.png")); // NOI18N
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 30, 50));

        btnAccount.setkBorderRadius(0);
        btnAccount.setkEndColor(new java.awt.Color(204, 153, 255));
        btnAccount.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        btnAccount.setkHoverForeGround(new java.awt.Color(255, 102, 255));
        btnAccount.setkHoverStartColor(new java.awt.Color(255, 163, 255));
        btnAccount.setkStartColor(new java.awt.Color(204, 153, 255));
        btnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 210, 50));

        lbDashboard.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lbDashboard.setText("Log out");
        kGradientPanel1.add(lbDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 120, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\vomin\\Downloads\\icons8-logout-rounded-left-24.png")); // NOI18N
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 30, 50));

        btnLogout.setkBorderRadius(0);
        btnLogout.setkEndColor(new java.awt.Color(204, 153, 255));
        btnLogout.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        btnLogout.setkHoverForeGround(new java.awt.Color(255, 102, 255));
        btnLogout.setkHoverStartColor(new java.awt.Color(255, 153, 255));
        btnLogout.setkStartColor(new java.awt.Color(204, 153, 255));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 210, 50));

        lbManagement.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbManagement.setForeground(new java.awt.Color(255, 255, 255));
        lbManagement.setText("Management");
        kGradientPanel1.add(lbManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 120, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\vomin\\OneDrive\\Máy tính\\icons8-add-user-male-18.png")); // NOI18N
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 30, 50));

        btnManagement.setkBorderRadius(0);
        btnManagement.setkEndColor(new java.awt.Color(204, 153, 255));
        btnManagement.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        btnManagement.setkHoverForeGround(new java.awt.Color(255, 102, 255));
        btnManagement.setkHoverStartColor(new java.awt.Color(255, 153, 255));
        btnManagement.setkStartColor(new java.awt.Color(204, 153, 255));
        btnManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagementActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 210, 50));

        lbOrder.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbOrder.setForeground(new java.awt.Color(255, 255, 255));
        lbOrder.setText("Order");
        kGradientPanel1.add(lbOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 120, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\vomin\\OneDrive\\Máy tính\\icons8-shopping-cart-18.png")); // NOI18N
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 30, 50));

        btnOrder.setkBorderRadius(0);
        btnOrder.setkEndColor(new java.awt.Color(204, 153, 255));
        btnOrder.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        btnOrder.setkHoverForeGround(new java.awt.Color(255, 102, 204));
        btnOrder.setkHoverStartColor(new java.awt.Color(255, 153, 255));
        btnOrder.setkStartColor(new java.awt.Color(204, 153, 255));
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 210, 50));

        lbWorkbench.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbWorkbench.setForeground(new java.awt.Color(255, 255, 255));
        lbWorkbench.setText("Workbench");
        kGradientPanel1.add(lbWorkbench, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\vomin\\OneDrive\\Máy tính\\icons8-home-18.png")); // NOI18N
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 30, 50));

        btnWorkbench.setkBorderRadius(0);
        btnWorkbench.setkEndColor(new java.awt.Color(204, 153, 255));
        btnWorkbench.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        btnWorkbench.setkHoverForeGround(new java.awt.Color(255, 102, 255));
        btnWorkbench.setkHoverStartColor(new java.awt.Color(255, 153, 255));
        btnWorkbench.setkStartColor(new java.awt.Color(204, 153, 255));
        btnWorkbench.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkbenchActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnWorkbench, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 210, 50));

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 250, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        new Welecome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        CheckInputTaiKhoan checkInputTaiKhoan = new CheckInputTaiKhoan();
            if(String.valueOf(pwfMoi.getPassword()).equals(""))
            JOptionPane.showMessageDialog(rootPane, "Mật khẩu không hợp lệ");
            else{
                if(String.valueOf(pwfNhaplai.getPassword()).equals(String.valueOf(pwfMoi.getPassword()))==false)
                    JOptionPane.showMessageDialog(rootPane, "Nhập lại sai mật khẩu");
                else{
                    Dang_Nhap.tkDangnhap.setPassword(String.valueOf(pwfNhaplai.getPassword()));
                    try {
                        new TaiKhoanDAO().doimatkhau(Dang_Nhap.tkDangnhap);
                        JOptionPane.showMessageDialog(rootPane, "Đổi mật khẩu thành công");
                    } catch (Exception e) {
                        System.out.println(e.getMessage());
                        e.printStackTrace();
                }
            }
        }        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnStaticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaticsActionPerformed
        // TODO add your handling code here:
        new StaticsFormChoose().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStaticsActionPerformed

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        // TODO add your handling code here:
        new TTCaNhan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAccountActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new Dang_Nhap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagementActionPerformed
        // TODO add your handling code here:
        new MagementForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManagementActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // TODO add your handling code here:
        new OrderFormChoose().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnWorkbenchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkbenchActionPerformed
        // TODO add your handling code here:
        new Welecome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnWorkbenchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TTCaNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TTCaNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TTCaNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TTCaNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>t
        //</editor-fold>
        //</editor-fold>t

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TTCaNhan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnAccount;
    private com.k33ptoo.components.KButton btnLogout;
    private com.k33ptoo.components.KButton btnManagement;
    private com.k33ptoo.components.KButton btnOrder;
    private com.k33ptoo.components.KButton btnReset;
    private com.k33ptoo.components.KButton btnStatics;
    private com.k33ptoo.components.KButton btnThoat;
    private com.k33ptoo.components.KButton btnWorkbench;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private com.k33ptoo.components.KButton kButton11;
    private com.k33ptoo.components.KButton kButton13;
    private com.k33ptoo.components.KButton kButton14;
    private com.k33ptoo.components.KButton kButton8;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel lbAccount;
    private javax.swing.JLabel lbAnh;
    private javax.swing.JLabel lbChucvu;
    private javax.swing.JLabel lbDashboard;
    private javax.swing.JLabel lbDiachi;
    private javax.swing.JLabel lbGioitinh;
    private javax.swing.JLabel lbHoten;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbManagement;
    private javax.swing.JLabel lbManv;
    private javax.swing.JLabel lbNgaysinh;
    private javax.swing.JLabel lbOrder;
    private javax.swing.JLabel lbSdt;
    private javax.swing.JLabel lbStatics;
    private javax.swing.JLabel lbWorkbench;
    private javax.swing.JPasswordField pwfCu;
    private javax.swing.JPasswordField pwfMoi;
    private javax.swing.JPasswordField pwfNhaplai;
    // End of variables declaration//GEN-END:variables
}
